### ISSUE TITLE
gd cologne

### ISSUE THREAD

**Issue by eveee00** [geometrylite/geometrylite.github.io#6]
I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

EDIT: i use ~~Arch~~ EndeavourOS btw

![grafik](https://github.com/geometrylite/geometrylite.github.io/assets/83956322/8b4cd26e-5419-4954-b43a-52d65a3c120a)

**Comment by NexusSfan** [comment]
W

**Comment by ghost** [comment]
![image](https://github.com/geometrylite/geometrylite.github.io/assets/85982640/c15b87b3-a214-4691-bc3f-40c7eaa05b11)

**Comment by Icey67** [comment]
![Image](https://github.com/user-attachments/assets/231200b5-e8ad-4dfa-b40c-f7c5a750748c)

**Comment by NexusSfan** [comment]
> ![Image](https://github.com/user-attachments/assets/231200b5-e8ad-4dfa-b40c-f7c5a750748c)

proprietary

**Comment by ghost** [comment]
why do i have this thread watched

**Comment by eveee00** [comment]
idk lmao

**Comment by NexusSfan** [comment]
me too

**Comment by Icey67** [comment]
fellow thread watchers, look at this shit
[![Image](https://github.com/user-attachments/assets/9969beab-37ec-4364-8c99-f153e930edee)](https://github.com/Icey67/Lenovo-IdeaPad-S145-15IWL-OpenCore-EFI)
